services:
  App\Application\EventListener\SomeEventListener:
  App\Application\Http\Handler\HomePage:
  App\Application\Http\Handler\AddTodo:
  App\Application\Http\Handler\RemoveTodo:
  App\Application\Http\Handler\EditTodo:
  App\Application\Http\Middleware\ValidateTodoRequest:
  Psr\Log\LoggerInterface:
    factory: [Antidot\Logger\Container\MonologFactory]
  App\Domain\TodosRepository:
    factory: [Antidot\Persistence\Doctrine\Container\EntityRepositoryFactory, 'App\Domain\Model\Todo']
  Antidot\Render\TemplateRenderer:
    factory: [Antidot\Render\Phug\Container\PugRendererFactory]

parameters:
  debug: false
  config_cache_enabled: true
  monolog:
    handlers:
      default:
        type: 'stream'
        options:
          stream: 'var/log/%date%-default.log'
          level: 400
  doctrine:
    connection:
      orm_default:
        driver_class: Doctrine\DBAL\Driver\PDOSqlite\Driver
        params:
          path: 'var/database.sqlite'
    driver:
      orm_default:
        paths:
          config/doctrine: App\Domain\Model